baseurl = "http://blog.hugoexample.com/"
languageCode = "en-us"
title = "SoftLayer API Examples"
canonifyurls = true
SectionPagesMenu = "sections"
pygmentsuseclasses = false
pygmentsStyle = "monokai"

[taxonomies]
	tag = "tags"
	class = "classes"

pluralizeListTitles = false

[[menu.main]]
    name = "perl"
    identifier = "perl"
    url = "/perl/"
[[menu.main]]
    name = "php"
    identifier = "php"
    url = "/php/"
[[menu.main]]
    name = "python"
    identifier = "python"
    url = "/python/"
[[menu.main]]
    name = "ruby"
    identifier = "ruby"
    url = "/ruby/"
[[menu.main]]
    name = "tools"
    identifier = "tools"
    url = "/tools/"
