baseurl = "http://blog.hugoexample.com/"
languageCode = "en-us"
title = "SoftLayer API Examples"
canonifyurls = true
SectionPagesMenu = "sections"
pygmentsuseclasses = false
pygmentsStyle = "monokai"

